services:
  apache:
    build:
      context: ./  # Point to the root of the project for apache
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./configs/apache.local.conf:/usr/local/apache2/conf/httpd.conf
      - ./web/static:/usr/local/apache2/htdocs/
    networks:
      - backend
    depends_on:
      - myapp

  myapp:
    build:
      context: ./  # Point to the root of the project for Go app
      dockerfile: ./docker/myapp/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
